---
pool: 
  vmImage: ubuntu-20.04

trigger:
  - REL_INT_2.0


steps:
  - task: Maven@3
    inputs:
     mavenPomFile: 'pom.xml'
     goals: 'package'
     publishJUnitResults: yes
     testResultsFiles: '**/surefire-reports/TEST-*.xml'
     jdkVersionOption: '1.11'


